dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.4
gemfile:
  - Gemfile

before_install:
  - TAG=$(git describe --tags)
  - echo "export rvm_ignore_gemsets_flag=1" >> ~/.rvmrc
  - gem install bundler -v 1.15.1

install:
  - bundle install --jobs=4 --retry=3 --path vendor/bundle
  - echo $TAG | tr -d v,V > VERSION

script:
  - bundle exec rspec spec

deploy:
  provider: script
  on:
    tags: true
  skip_cleanup: true # prevent removing vendored gems needed by deploy scropt
  script: rvm $TRAVIS_RUBY_VERSION --verbose do ./deploy.sh # dpl runs script in another ruby env, need to switch back with rvm

env:
  global:
    - TZ='US/Eastern'
    # GEM_PASSWORD
    - secure: AO8qnqJOzHOUDIdiin1jDDjebYUIwMMyRT6fJbIjg7BmomMTcaXimQcFLZf9tsLbEf9bCGZ6Wia4m63KvvAzIbJTNveXIxETXc/P+zvvt/u0VrnLiU9sS4khQGojhx9O2K6DmpwLhrXuFv7bxO0o4VwE7PsiAaczDEzvFWJUlfMiD2rhlKSJ4S8oELYAvX8GprVWVTysofSRbc9v7tPSCCRQTJNq7raNmJOU5R8P50p8zhUYP0gtnrOYPZtknqc1EP0dRqUOh3GP6nIGoPX5XeqswJ7lnYZZg4jbNx/+Q4bYOOQ4I+O7VStUBceUIjL7Tic2LNZrgET9wfXhHONHtu3/W0Z0p1RXV9Qm+QPUHuMx/rA88iVPX9SDvIGhR5GGsnMcLwfstl79lyXrnwwekW8xiTl+PbMPUQWR/nCRgR7n0QL9MqVSkJW+W85HyUtxMqBW576tKvxo8it4aYI95TeFmgoUL9FWUg/9eoJ2BNjl73W1RC0xmqTKe1L964TY+tJnsKHQEZlOoTfO0NQ8tmDMBDyPm9MPN+8Akq5AxLc4GsQmD47X7NJ2uFRW6aBsM53rjx33dnr5zDMiCHK+e626Hi41/9bH5KvIXxMSVOMQl5/derUs26UDondi36Td85P0FT/QtuVKQ/CsDczQwHHql9A7eJJI9529X12YBCA=

notifications:
  slack:
    secure: PyjyVA4cTEM2GMgodFl1KjEt/6FDqGSq82HmYk254mm0x65pIiE688XnPiNJGygk+w544PwQ0c9Z19ijkAKUustuXAfc5f9/rtedUAtjq12m61rVF+TeLMjVBc2A7mHcb/Yg2y/kgO6PESQLsrTSIAqXrO/srgfPGvuvLAsh0yy3KG7ZFX3sJu1kqzk0osE11MHhDZQGH5ABjuMp6DLLJtPbLe7Ei0n6T46peEcxVcQu4BMFTKvcCjbUQQmKNz3pTFlYEceZMhhO6+GbXbT47hD+6rFAMs91bT7v+kdg8ARsH+PSdHiPzp8Kuh3wuivgnJscjIalghCD5WgwKwvrEDRvAi75d2wNPaeN6D//tVRdkx3DBXOS1oDdsc4W3vtO3FNnuEAvMXj2KAkfgEJIhblR7cJB0+cWbcIKVVIB/k4Fa14Xx06fgxLnf/oYt/utRj7sVmvDlvqttDqcLryFQwHMQ6mYeFr8lLoBSGp7IP4d+4dRSXVrKmSvE1ZXJAFpo+Qb/oBqAxJT0JJ+tCBUL/h8VQFni9UyLHhJJhnjuoTy4vrtEALp263L8TnRhUJhvfDxbuNhKSh6n5nuSowkp8gTklP6pJGMQafvcbEqTdHqQMLOJpRhrzCKhVP0QCo4FW4lu39mIkeYO+hPkCOCVF/KcugPwvvbfR82D8tZWzw=
